blank_issues_enabled: false
contact_links:
    - name: Bug or technical issue
      url: https://github.com/iamdadmin/yaeslpt/issues/new
      about: Report a reproducable bug
    - name: Feature or improvement
      url: https://github.com/iamdadmin/yaeslpt/issues/new
      about: Request a feature or improvement

